# Generated by Django 2.0.6 on 2020-09-11 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=20)),
                ('main_pic', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=20)),
                ('publisher', models.CharField(max_length=20)),
                ('publish_date', models.DateField()),
                ('origin_price', models.IntegerField()),
                ('dangdang_price', models.IntegerField()),
                ('number', models.IntegerField()),
                ('traffic', models.IntegerField()),
                ('comment_number', models.IntegerField()),
            ],
            options={
                'db_table': 't_book',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BookDetail',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('version', models.IntegerField()),
                ('page_number', models.IntegerField()),
                ('word_number', models.IntegerField()),
                ('print_date', models.DateField()),
                ('format', models.IntegerField()),
                ('page_type', models.CharField(max_length=10)),
                ('print_number', models.IntegerField()),
                ('pack_type', models.CharField(max_length=10)),
                ('is_suit', models.IntegerField()),
                ('isbn', models.IntegerField()),
            ],
            options={
                'db_table': 't_book_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BookDisplay',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('editor_recommend', models.CharField(max_length=100)),
                ('content_recommend', models.CharField(max_length=100)),
                ('author_summarize', models.CharField(max_length=100)),
                ('media_comment', models.CharField(max_length=100)),
                ('part_content', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 't_book_display',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('level', models.IntegerField()),
                ('parent_id', models.IntegerField()),
            ],
            options={
                'db_table': 't_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pic',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('pic_1', models.CharField(max_length=50)),
                ('pic_2', models.CharField(max_length=50)),
                ('pic_3', models.CharField(max_length=50)),
                ('pic_4', models.CharField(max_length=50)),
                ('pic_5', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 't_pic',
                'managed': False,
            },
        ),
    ]
