# Generated by Django 2.0.6 on 2020-09-11 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('detail_address', models.CharField(max_length=100)),
                ('post_code', models.IntegerField()),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('tele_number', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_harvest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20)),
                ('user_pwd', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 't_user',
                'managed': False,
            },
        ),
    ]
